# Step 5 - Install gitlab via docker

# Next step to create docker compose file for gitlab


web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com:3200'
  # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '3200:3200'
    - '443:443'
    - '2222:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
